---

project:
  name: "go-rest"
  description: "rest service implemewntation inspired by Mat Ryer"
  author: "Sascha Andres"
  repository: "https://github.com/sascha-andres/go-rest"
  default-branch: "master"

transformation:
  explicit-templates: false
  excluded-files:
    - ".go-template.yml"
  templates:
    - "test.go"
  renames:
    - from: "go-rest/"
      to: "{{ .Name }}"
      type: "directory"